name = "summer-river-8271"
main = "worker.js"
compatibility_date = "2026-08-20"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "harvester-turtle-db"
database_id = "0e3091fd-dcd6-488d-a0f6-896ab2e55225"
